name: supabase

ingress:
  rules:
    - match:
        path:
          prefix: /rest/v1
      component:
        name: rest
        rewrite: /
    - match:
        path:
          prefix: /
      component:
        name: studio

services:
  - name: studio
    image:
      registry_type: DOCKER_HUB
      registry: supabase
      repository: studio
      tag: latest
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    health_check:
      http_path: /api/platform/profile
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      failure_threshold: 3
    envs:
      - key: STUDIO_PG_META_URL
        value: http://meta:8080
      # Database connection details (for Studio dashboard display)
      - key: POSTGRES_HOST
        scope: RUN_TIME
        value: ${supabase-db.HOSTNAME}
      - key: POSTGRES_PORT
        scope: RUN_TIME
        value: ${supabase-db.PORT}
      - key: POSTGRES_DB
        scope: RUN_TIME
        value: ${supabase-db.DATABASE}
      - key: POSTGRES_USER
        scope: RUN_TIME
        value: ${supabase-db.USERNAME}
      - key: POSTGRES_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: ${supabase-db.PASSWORD}
      # Encryption key for Studio-Meta communication
      # Studio encrypts connection strings using PG_META_CRYPTO_KEY (with username: supabase_admin)
      # Meta decrypts using CRYPTO_KEY
      - key: PG_META_CRYPTO_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${CRYPTO_KEY}
      - key: DEFAULT_ORGANIZATION_NAME
        value: "My Organization"
      - key: DEFAULT_PROJECT_NAME
        value: "My Project"
      - key: SUPABASE_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: SUPABASE_PUBLIC_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: SUPABASE_ANON_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${SUPABASE_ANON_KEY}
      - key: SUPABASE_SERVICE_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${SUPABASE_SERVICE_ROLE_KEY}
      - key: NEXT_PUBLIC_ENABLE_LOGS
        value: "false"

      # Template Tracking (for DigitalOcean analytics)
      - key: APPPLAT_BASE_TEMPLATE
        value: "supabase"
      - key: APPPLAT_TEMPLATE_TYPE
        value: "simple"
      - key: APPPLAT_TEMPLATE_COMMIT_SHA
        value: ${_self.COMMIT_HASH}

  # PostgREST - Auto-generated REST API
  # Version pinned to v12.2.3 for API stability
  - name: rest
    image:
      registry_type: DOCKER_HUB
      registry: postgrest
      repository: postgrest
      tag: v12.2.3
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3
      failure_threshold: 3
    envs:
      - key: PGRST_DB_URI
        scope: RUN_TIME
        value: ${supabase-db.DATABASE_URL}
      - key: PGRST_DB_SCHEMAS
        value: public
      # Anonymous role for unauthenticated requests
      # Created by db-init job on managed database
      - key: PGRST_DB_ANON_ROLE
        value: anon
      - key: PGRST_DB_POOL
        value: "10"
      - key: PGRST_SERVER_PORT
        value: "3000"
      # JWT Configuration (required for authentication)
      - key: PGRST_JWT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: ${SUPABASE_JWT_SECRET}
      - key: PGRST_JWT_AUD
        value: authenticated

  # Meta - Database Management API (internal only, accessed by Studio)
  - name: meta
    image:
      registry_type: DOCKER_HUB
      registry: supabase
      repository: postgres-meta
      tag: latest
    internal_ports:
      - 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    envs:
      - key: PG_META_PORT
        value: "8080"
      - key: PG_META_DB_HOST
        scope: RUN_TIME
        value: ${supabase-db.HOSTNAME}
      - key: PG_META_DB_PORT
        scope: RUN_TIME
        value: ${supabase-db.PORT}
      - key: PG_META_DB_NAME
        scope: RUN_TIME
        value: ${supabase-db.DATABASE}
      - key: PG_META_DB_USER
        value: supabase_admin
      - key: PG_META_DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: ${supabase-db.PASSWORD}
      # SSL configuration for managed database connections
      - key: PG_META_DB_SSL_MODE
        value: "require"
      - key: PG_META_DB_SSL_ROOT_CERT
        scope: RUN_TIME
        value: ${supabase-db.CA_CERT}
      # Decryption key for Studio's encrypted connection strings
      # Must match Studio's PG_META_CRYPTO_KEY
      - key: CRYPTO_KEY
        scope: RUN_TIME
        type: SECRET
        value: ${CRYPTO_KEY}

jobs:
  # Database Initialization (runs before services start)
  - name: db-init
    kind: PRE_DEPLOY
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb

    github:
      repo: AppPlatform-Templates/supabase-appplatform
      branch: main

    dockerfile_path: db-init/Dockerfile.dbinit

    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${supabase-db.DATABASE_URL}

databases:
  - name: supabase-db
    engine: PG
    production: true
    version: "17"
    cluster_name: supabase-db
